# Default values for wildfly
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  tag: latest
build:
  uri: https://github.com/jboss-eap-up-and-running/eap8-getting-started.git
  enabled: true
  mode: s2i
  s2i:
    buildApplicationImage: true
    kind: DockerImage
    jdk: "17"
    jdk17:
      builderImage: registry.redhat.io/jboss-eap-8/eap8-openjdk17-builder-openshift-rhel8:latest
      runtimeImage: registry.redhat.io/jboss-eap-8/eap8-openjdk17-runtime-openshift-rhel8:latest
  output:
    kind: "ImageStreamTag"
  triggers: {}
deploy:
  enabled: true
  replicas: 1
  tls: {}
  route:
    enabled: true
    tls:
      enabled: true
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  livenessProbe:
    httpGet:
      path: /health/live
      port: admin
    initialDelaySeconds: 60
  readinessProbe:
    httpGet:
      path: /health/ready
      port: admin
    initialDelaySeconds: 10
  startupProbe:
    httpGet:
      path: /health/live
      port: admin
    initialDelaySeconds: 60