# Default values for wildfly
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  tag: latest
build:
  uri: https://github.com/jboss-eap-up-and-running/eap82-getting-started.git
  enabled: true
  mode: s2i
  bootableJar:
    builderImage: registry.access.redhat.com/ubi10/openjdk-21:latest
  s2i:
    buildApplicationImage: true
    kind: DockerImage
    jdk: "21"
    jdk21:
      builderImage: registry.redhat.io/jboss-eap-8-tech-preview/eap82-openjdk21-builder-openshift-rhel10:latest
      runtimeImage: registry.redhat.io/jboss-eap-8-tech-preview/eap82-openjdk21-runtime-openshift-rhel10:latest
    jdk25:
      builderImage: registry.redhat.io/jboss-eap-8-tech-preview/eap82-openjdk25-builder-openshift-rhel10:latest
      runtimeImage: registry.redhat.io/jboss-eap-8-tech-preview/eap82-openjdk25-runtime-openshift-rhel10:latest
  output:
    kind: "ImageStreamTag"
  triggers: {}
deploy:
  enabled: true
  replicas: 1
  tls: {}
  route:
    enabled: true
    tls:
      enabled: true
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  livenessProbe:
    httpGet:
      path: /health/live
      port: admin
  readinessProbe:
    httpGet:
      path: /health/ready
      port: admin
    initialDelaySeconds: 10
  startupProbe:
    httpGet:
      path: /health/started
      port: admin
    initialDelaySeconds: 10
    failureThreshold: 11