{{- if and .Values.build.enabled (eq .Values.build.mode "s2i") }}
{{- include "wildfly-common.buildconfig-s2i-build-artifacts" (list . "eap8.buildconfig-s2i-build-artifacts") -}}
{{- end -}}

{{- define "eap8.buildconfig-s2i-build-artifacts" -}}
{{ include "eap8.metadata.labels" . }}
spec:
  strategy:
    sourceStrategy:
      from:
        kind: {{ .Values.build.s2i.builderKind | default .Values.build.s2i.kind }}
        name: {{ include "eap8.eapBuilderImage" . }}
      env:
      - name: CUSTOM_INSTALL_DIRECTORIES
        value: extensions
      {{- if .Values.build.s2i }}
      {{- if .Values.build.s2i.galleonLayers }}
      - name: GALLEON_PROVISION_LAYERS
        value: {{ join "," .Values.build.s2i.galleonLayers | quote }}
      {{- end }}
      {{- if .Values.build.s2i.featurePacks }}
      - name: GALLEON_PROVISION_FEATURE_PACKS
        value: {{ join "," .Values.build.s2i.featurePacks | quote }}
      {{- end }}
      {{- if .Values.build.s2i.channels }}
      - name: GALLEON_PROVISION_CHANNELS
        value: {{ join "," .Values.build.s2i.channels | quote }}
      {{- end }}
      {{- if .Values.build.s2i.galleonDir }}
      - name: GALLEON_DIR
        value: {{ quote .Values.build.s2i.galleonDir }}
      {{- end }}
      {{- end }}
      {{- if .Values.build.env }}
      {{- tpl (toYaml .Values.build.env) . | nindent 6 }}
      {{- end }}

{{- end -}}