{{- if .Values.deploy.enabled }}
{{- include "wildfly-common.deployment" (list . "eap8.deployment") -}}
{{- end -}}

{{ define "eap8.deployment" }}
{{- include "eap8.deployment.labels" . }}
spec:
  template:
    {{- include "eap8.deployment.labels" . | nindent 4 }}
{{- end -}}