repo:
  - ./*
examples:
  - examples/*
charts:
  - charts/*
eap8:
  - charts/eap8/**/*
eap81:
  - charts/eap81/**/*
documentation:
  - ./README.md
  - charts/**/README.md
  - charts/**/values.schema.json
 
