# Deploy EAP applications on OpenShift with Helm Charts
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -
:keywords:          openshift,eap,helm

## Prerequisites

Until EAP 8 is released, the Helm Charts needs some prerequisites to use unreleased Maven repository and S2I images.

### Add EAP 8 Maven repository Docker image in OpenShift

Follow the instructions at https://github.com/jbossas/eap-charts/wiki/Build-with-unreleased-EAP-Maven-Repository

## Add unreleased S2I images in OpenShift

Follow the instructions at https://github.com/jbossas/eap-charts/wiki/Build-with-unreleased-EAP-S2I-images

## Add A ConfigMap for the Maven settings.xml

If you are not able to modify the application code to add a `ocp-settings.xml` to provision EAP 8, you need to create a ConfigMap that contains that file and inject it during S2I build

ocp-setting.xml
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>

<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
    <profiles>
        <!-- Configure the JBoss EAP Maven repository -->
        <profile>
            <id>jboss-eap-repository</id>
            <repositories>
                <repository>
                    <id>jboss-eap-repository</id>
                    <url>file:///tmp/src/eap-maven-repo/maven-repository</url>
                </repository>
                <repository>
                    <id>central</id>
                    <url>https://repo1.maven.org/maven2/</url>
                </repository>
                <repository>
                    <id>redhat-ga-repository</id>
                    <url>https://maven.repository.redhat.com/ga/</url>
                </repository>
            </repositories>
            <pluginRepositories>
                <pluginRepository>
                    <id>jboss-eap-plugin-repository</id>
                    <url>file:///tmp/src/eap-maven-repo/maven-repository</url>
                </pluginRepository>
                <pluginRepository>
                    <id>central</id>
                    <url>https://repo1.maven.org/maven2/</url>
                </pluginRepository>
                <pluginRepository>
                    <id>redhat-ga-repository</id>
                    <url>https://maven.repository.redhat.com/ga/</url>
                </pluginRepository>
            </pluginRepositories>
        </profile>
    </profiles>

    <activeProfiles>
        <activeProfile>jboss-eap-repository</activeProfile>
    </activeProfiles>
</settings>
----

Create a `eap-maven-settings` ConfigMap that contains this file:

[source,bash]
----
oc create configmap eap-maven-settings --from-file=settings.xml=./ocp-settings.xml
----

## Build and Deploy the Application

You can deploy the application using the `helm` tool:

[source,options="nowrap"]
----
$ helm install eap8-app \
  -f ./helm.yaml \
  -f ./eap8-dev.yaml \
  --repo https://jmesnil.github.io/eap-charts/ eap8
LAST DEPLOYED: Mon Feb 15 16:39:26 2021
...
STATUS: deployed
REVISION: 1
----

You also need to patch the BuildConfig to use the `eap-maven-settings` configmap
and trigger a new build to take into account the patch

[source,bash]
----
oc patch buildconfig eap8-app-build-artifacts --patch-file ./eap-mvn-settings-patch.yaml
oc start-build eap8-app-build-artifacts
----

Let's wait for the application to be built and deployed:

[source,options="nowrap"]
----
$ oc get deployment helloworld-rs-app -w
NAME                READY   UP-TO-DATE   AVAILABLE   AGE
helloworld-rs-app   0/3     3            0           72s
...
helloworld-rs-app   3/3     3            3           6m11s
----

Once the application is deployed, it can be accessed from the route `helloworld-rs-app `:

[source,options="nowrap"]
----
curl -L  http://$(oc get route helloworld-rs-app -o jsonpath="{.spec.host}")/rest/json
{"result":"Hello World!"}%
----

The application can be deleted by running the command:

[source,options="nowrap"]
----
$ helm delete helloworld-rs-app
release "helloworld-rs-app" uninstalled
----