# Install a EAP 8.2 Application
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -
:keywords:          openshift,wildfly,microprofile,helm

This example shows how to deploy a Java application with EAP 8.2 on OpenShift.

## Prerequisites

## Source Code

The source code for the backend is hosted at https://github.com/jboss-eap-up-and-running/eap82-getting-started.git

It is a simple application that uses JAX-RS to exposes HTTP endpoint.

## Installation

[source,options="nowrap"]
----
$ helm install eap82-app -f examples/eap82/getting-started/app.yaml ./charts/eap82
----

## Deployment

Once the chart is installed, let's wait for the application to be built and deployed:

[source,options="nowrap"]
----
$ oc get deployment/eap82-app -w
NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
eap82-app                 0/1     1            0           27s
...
eap82-app                 1/1     1            1           5m29s
----

## Use the application

Once the application is deployed on OpenShift, it can be accessed from the route `eap82-app`.
Let's find the host that we can use to connect to this backend:

[source,options="nowrap"]
----
$ oc get route eap82-app -o jsonpath="{.spec.host}"
eap82-app-jmesnil1-dev.apps.sandbox.x8i5.p1.openshiftapps.com
----

This value will be different for every installation of the application.

We can then query this application by calling its HTTP endpoint from the URL above.

## Clean up

The application can be deleted by running the command:

[source,options="nowrap"]
----
$ helm delete eap82-app 
release "eap82-app " uninstalled
----